### PR TITLE
added link to help menu

### PR DESCRIPTION
**Pull request by olisakov**
[SDA-5618](https://issues.redhat.com/browse/SDA-5618)
@pvasant @tzvatot

### CODE REVIEW

**Comment by pvasant** [comment]
@olisakov ones inside vendor pkg are auto generated. You need to change the original file.

**Comment by olisakov** [comment]
@zvikorn

**Comment by zvikorn** [comment]
LGTM

**Comment by tzvatot** [comment]
LGTM

**Pull request merged**
