### PR TITLE
Delete roles with managed policies

### PR DESCRIPTION
**Pull request by oriAdler**
Skip the policy deletion for managed policies.

Related: [SDA-7728](https://issues.redhat.com/browse/SDA-7728)

image

image

### CODE REVIEW

**Comment by oriAdler** [comment]
@gdbranco @hunterkepley @zgalor PTAL

**Comment by gdbranco** [comment]
I feel like we are adding managed policies bool to a lot of functions. Personally, I would rather separate these into two as they are slightly different. We might want to refactor at some point

But I'm okay if you would like to merge as is

**Comment by oriAdler** [comment]
> I feel like we are adding managed policies bool to a lot of functions. Personally, I would rather separate these into two as they are slightly different. We might want to refactor at some point
> 
> But I'm okay if you would like to merge as is

I agree we can take advantage of go design patterns to differentiate the cases.
As for now, I'm satisfied with the approach of passing a boolean.
We can do more refactoring in the future, once functionality is in place.

**Pull request merged**
