### PR TITLE
Interactive validation

### PR DESCRIPTION
**Pull request by vkareh**
This adds interactive validation so that the program does not exit on bad input, instead it displays the error and re-prompts the user.

Demo: https://asciinema.org/a/sFXGyyEcv1y6inoGiBEEXrjWI

### CODE REVIEW

**Comment by zgalor** [comment]
Very nice!
How can we avoid duplicating the validation code between interactive mode and user flag inputs?

**Comment by vkareh** [comment]
@zgalor
> How can we avoid duplicating the validation code between interactive mode and user flag inputs? 

I've been thinking about this, and I want to try writing an `input` wrapper that takes the flag info and the validator, then depending on whether the interactive mode is enabled or not, it would display the prompt or just validate the existing data. This would be a large change, probably better suited for a future improvement.

**Comment by pvasant** [comment]
this is nice. looks good to me

**Pull request merged**
