### PR TITLE
OCM-6222 | feat: Add Critical and High labels to all tests

### PR DESCRIPTION
**Pull request by hunterkepley**
**This is a work in progress, you can help by determining which tests shouldn't have these tags, or if there are any important tests I missed**

General guidelines for High/Critical tags:

Critical
---
Affects creation and deletion of clusters

High
---
Affects updates/scaling of clusters

https://issues.redhat.com/browse/OCM-6222

### CODE REVIEW

**Comment by robpblake** [comment]
@hunterkepley Do you have a bit more context? The linked Jira issue says the motivation for this is to cut costs? I don't see how this impacts costs of running our CI pipeline as our unit tests are just a single container execution.

**Comment by hunterkepley** [comment]
> @hunterkepley Do you have a bit more context? The linked Jira issue says the motivation for this is to cut costs? I don't see how this impacts costs of running our CI pipeline as our unit tests are just a single container execution.

https://docs.google.com/document/d/14sMDCepP_-6HWHQD0aa5eK1wdnVuJgmMEuAYAteMk0o/edit

This DD should explain it better than I can @robpblake

**Pull request closed without merging**
