### PR TITLE
reprompt user when passed invalid addon argument

### PR DESCRIPTION
**Pull request by renan-campos**
The interactive mode was terminating if the user passed an invalid string argument when installing an addon.
This set of commits modifies the behavior of _interactive.GetAddonArgument()_ to continue prompting the user.

[SDA-6852](https://issues.redhat.com/browse/SDA-6852)

### CODE REVIEW

**Comment by renan-campos** [comment]
@laurafitzgerald PTAL

**Review by ciaranRoche — COMMENTED** [review]
From testing this it hangs if you repeatedly enter the wrong value

**Comment by renan-campos** [comment]
> From testing this it hangs if you repeatedly enter the wrong value

pushed a change addressing this issue and the problem with the default value.

**Pull request merged**
