### PR TITLE
Update to version 4 of JWT library

### PR DESCRIPTION
**Pull request by vkareh**
Since OCM SDK updated to jwt v4, we update ROSA's own import to match. This avoids possible breakages when using the `jwt.Token` within the request context.

### CODE REVIEW

**Review by jharrington22 — COMMENTED** [review]
@vkareh this looks good to me, ready to merge?

**Comment by vkareh** [comment]
@jharrington22 

ready to merge!

**Comment by jharrington22** [comment]
@vkareh looks like prow isn't happy, linting is fine for me locally with go 1.16 but I can replicate the errors with 1.15. Are you using 1.16 locally? I can bump the CI job config if you can update the go mod ref to Go 1.15?

**Comment by vkareh** [comment]
@jharrington22 - just bumped to 1.16. Locally I use 1.17.5, but not sure that 1.17 is available in RHEL8, which will mess with the RPM build pipelines.

**Comment by jharrington22** [comment]
Once this merges linting should pass https://github.com/openshift/release/pull/25107

**Comment by jharrington22** [comment]
Nice!

/hold cancel

**Review by jharrington22 — APPROVED** [review]
/lgtm

**Pull request merged**
