### PR TITLE
Bump OCM-SDK to 0.1.266

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
@vkareh PTAL, first step for the STS work (trying to break it up to smaller changes)

**Comment by vkareh** [comment]
Thanks @tbrisker 
Can you run `go mod tidy` and rebuild the templates, please?

**Comment by tbrisker** [comment]
@vkareh updated

**Comment by vkareh** [comment]
/lgtm

Thanks!

**Pull request merged**
