### PR TITLE
fixes keycloak url aliases

### PR DESCRIPTION
**Pull request by markturansky**

### CODE REVIEW

**Comment by vkareh** [comment]
@markturansky can you add more context (and git commit description)?

Also, are we committing to these URLs? Merging this will effectively break any current customer using this CLI, as their tokens will all fail.

**Comment by vkareh** [comment]
@markturansky you will need to update all of the values in `ClientIDs` as well, as the ones in the code are specific for Cognito.

**Comment by tylercreller** [comment]
should be closed in favor of https://github.com/openshift/rosa/pull/1341

**Comment by vkareh** [comment]
Closing in favour of #1341

**Pull request closed without merging**
