### PR TITLE
fix - Google IDP doesn't work when created with ROSA CLI

### PR DESCRIPTION
**Pull request by zvikorn**
Signed-off-by: Tzvika Avni <tavni@redhat.com>

[SDA-6472](https://issues.redhat.com//browse/SDA-6472)

@zgalor @oriAdler @pvasant PTAL

### CODE REVIEW

**Comment by zvikorn** [comment]
@ciaranRoche can you ok-to-test again?

**Comment by faldanarh** [comment]
Hi, Guys.
Just wondering the current status for this fix.
Thanks.

**Comment by zgalor** [comment]
@zvikorn anything missing for this to be merged?

**Comment by zvikorn** [comment]
@zgalor nope. Just lgtm

**Pull request merged**
