### PR TITLE
[SDA-6886] Added RedHatManaged=true to manual operator/account/user roles creation

### PR DESCRIPTION
**Pull request by hunterkepley**
[SDA-6886](https://issues.redhat.com/browse/SDA-6886)

Fixes bug 6886 by adding RedHatManaged=true to manual creation of user/account/operator roles.

### CODE REVIEW

**Comment by pvasant** [comment]
@hunterkepley there are some lint failures

**Comment by hunterkepley** [comment]
> @hunterkepley there are some lint failures

@pvasant Victor is finishing up a fix, it's unrelated to this MR

**Pull request merged**
