### PR TITLE
OCM-8221 | test: fixed id:43067,70859,45161,43070,61322 and enhanceme…

### PR DESCRIPTION
**Pull request by yuwang-RH**
[OCM-8221](https://issues.redhat.com//browse/OCM-8221) | test: fixed id:43067,70859,45161,43070,61322 and enhancement for 44511,45176
fix:
43070/61322/44511/45176 : to use dynamic version
43067 : update the error message
70859 : Add condition of checking if the cluster is reusing oidcConfigID
45161 : remove base-domain flag to avoid its conflict

logs: https://privatebin.corp.redhat.com/?3a0245e924c18cf6#AENDhTF5XE5BQDYr5KsEZ9MJLqiXH57abKx5o2H7Z98j

### CODE REVIEW

**Comment by yuwang-RH** [comment]
@xueli181114 @yasun1 Could you help review this PR?Thanks

**Comment by yasun1** [comment]
The cases are `Day3` and `Day1Nagative`. They are not supported with the presubmit jobs before https://github.com/openshift/release/pull/52345 is merged. Using the local log to check result, and add LGTM

/lgtm

**Pull request merged**
