### PR TITLE
OCM-3334 | feat: allow setting GPU limitations

### PR DESCRIPTION
**Pull request by osherdp**
This adds support for setting the missing field of GPU limitations. Users are able to provide it via two options:
* CLI, by repeating the option multiple times. E.g.:

```
rosa create cluster --autoscaler-gpu-limit nvidia.com/gpu,0,10 --autoscaler-gpu-limit amd.com/gpu,1,5
```
* Interactively. E.g.:
```
rosa create cluster
...
? Enter the number of GPU limitations you wish to set (optional): 2
? 1. Enter the type of desired GPU limitation: nvidia.com/gpu
? 1. Enter minimum number of GPUS of type 'nvidia.com/gpu' to deploy in
the cluster. (optional): 0
? 1. Enter maximum number of GPUS of type 'nvidia.com/gpu' to deploy in
the cluster. (optional): 10
? 2. Enter the type of desired GPU limitation: amd.com/gpu
? 2. Enter minimum number of GPUS of type 'amd.com/gpu' to deploy in the
cluster. (optional): 1
? 2. Enter maximum number of GPUS of type 'amd.com/gpu' to deploy in the
cluster. (optional): 5
```

This is a rewrite of https://github.com/openshift/rosa/pull/1438 to adapt it to the code after a refactor. In addition it also sets a way to configure the GPU limitations via CLI arguments.

### CODE REVIEW

**Comment by osherdp** [comment]
/hold
doing some more testing

**Comment by osherdp** [comment]
All testing is done!
/unhold

**Comment by Gregory-Pereira** [comment]
Thanks, this implementation looks great.
/lgtm

**Pull request merged**
