### PR TITLE
OCM-3618 | feat: order imports - contributing file

### PR DESCRIPTION
**Pull request by oriAdler**
Highlight to format the files before creating a PR in the contribution file.

### CODE REVIEW

**Review by robpblake — APPROVED** [review]

**Comment by robpblake** [comment]
@oriAdler I think the missing `-` in your comment message for the JIRA ticket might be causing the pipeline to fail 🤔

**Comment by oriAdler** [comment]
> @oriAdler I think the missing `-` in your commit message for the JIRA ticket might be causing the pipeline to fail 🤔

Fixed, thanks

**Pull request merged**
