### PR TITLE
Fix bug - change the interactive message of `rosa delete user-role`

### PR DESCRIPTION
**Pull request by oriAdler**
Related: [SDA-5548](https://issues.redhat.com/browse/SDA-5548)

### CODE REVIEW

**Comment by oriAdler** [comment]
@zgalor @zvikorn @pvasant PTAL

**Comment by pvasant** [comment]
Do we need user role deletion mode?

**Comment by oriAdler** [comment]
> Do we need user role deletion mode?

Changed to `User role deletion mode`
We have both **manual** and **auto** mode similarly to `delete ocm-role` and `delete account-role`

**Pull request merged**
