### PR TITLE
adding new alias for managed service commands

### PR DESCRIPTION
**Pull request by renan-campos**

### CODE REVIEW

**Comment by vkareh** [comment]
The alias doesn't show up when calling `--help`. Do we want to make `managed-service` the default one? @arendej

**Comment by arendej** [comment]
> Do we want to make managed-service the default one? @arendej

Yes please

**Comment by renan-campos** [comment]
> > Do we want to make managed-service the default one? @arendej
> 
> Yes please

Changed it! Just fyi though: these commands are still hidden from `help`

**Comment by vkareh** [comment]
/lgtm

@arendej, I just want to voice my disapproval of the resource name. This should be `rosa create appliance`. Names like `"[Managed] Service"` are already overloaded... :stuck_out_tongue: 

Still, code change LGTM. Merging.

**Pull request merged**
