### PR TITLE
OCM-2180 | Fix: hide available upgrades for HCP in list versions

### PR DESCRIPTION
**Pull request by andreadecorte**
The target is to transition to cluster based updates recommandations,
which means no more available upgrades for a single version, only for a specific cluster.
So the rosa list version --hosted-cp should not show anymore the available upgrades,
as in any case the current list is not correct (also showing versions which are disabled for HCP).
The user is informed that it should use rosa list upgrades -c clusterID instead
No change for rosa classic versions.

CC @wgordon17 

Related: [OCM-2180](https://issues.redhat.com//browse/OCM-2180)

### CODE REVIEW

**Comment by wgordon17** [comment]
@andreadecorte Just confirming, so this PR will _remove_ the version list if a customer runs _specifically_ `rosa list versions --hosted-cp`, correct?

Do we have any other way for a customer to see what upgrades _are_ available to them? Like a `rosa list versions -c <cluster-name>`?

**Comment by andreadecorte** [comment]
> @andreadecorte Just confirming, so this PR will _remove_ the version list if a customer runs _specifically_ `rosa list versions --hosted-cp`, correct?

Correct.
> 
> Do we have any other way for a customer to see what upgrades _are_ available to them? Like a `rosa list versions -c <cluster-name>`?

We have a cluster aware command which is `rosa list upgrades -c <cluster>`.
The idea is that user uses that one (coupled with --control-plane/--machine-pool flags, not implemented yet) to see the list of available upgrades for the specific cluster.

**Comment by wgordon17** [comment]
That's excellent, thanks @andreadecorte!

Could we, for the specific use case of `rosa list versions --hosted-cp`, provide some kind of message or pointer to the `rosa list upgrades` option? Otherwise, I worry customers may get lost

**Comment by andreadecorte** [comment]
Added an info message:
```
rosa list version --channel-group=stable --hosted-cp
I: To list available upgrades, please use 'rosa list upgrades'
VERSION    DEFAULT
4.13.2     no
```

**Comment by andreadecorte** [comment]
@wgordon17 any other comments after the changes in https://github.com/openshift/rosa/pull/1307#issuecomment-1597212843 or can we proceed with this change?

**Comment by wgordon17** [comment]
+1 lgtm

**Pull request merged**
