### PR TITLE
SDA-5813: Updated SDK version and ran go mod vendor

### PR DESCRIPTION
**Pull request by hunterkepley**
[SDA-5813](https://issues.redhat.com/browse/SDA-5813)

This is an attempt to update the SDK in rosa as well as fix the pipeline failing: [View here](https://github.com/openshift/rosa/pull/797#issuecomment-1197115391)

### CODE REVIEW

**Comment by pvasant** [comment]
@yasun1  we have removed the display name from ocm SDK and prow build is not failing. can you please check if you are using it in your code somewhere ?

**Comment by yasun1** [comment]
@pvasant  I will check the issue and try to fix the image issue in Prow CI.

**Comment by yasun1** [comment]
Prow CI is crashed. Need to wait for the service is back.

**Comment by yasun1** [comment]
The rosa-aws-cli image build issue should be fixed by https://github.com/openshift/release/pull/30879.

**Comment by hunterkepley** [comment]
@oriAdler @zgalor  Passing now, PTAL :pray:

**Pull request merged**
