### PR TITLE
OCM-9940 | test: automated id:34950 check available regions

### PR DESCRIPTION
**Pull request by jerichokeyne**
Test output:
```
$ ginkgo run -focus id:34950 tests/e2e/
Running Suite: ROSA CLI e2e tests suite - /home/jericho/work/repos/rosa/tests/e2e
=================================================================================
Random Seed: 1727380075

Will run 1 of 235 specs
SSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS

Ran 1 of 235 Specs in 2.828 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 234 Skipped
PASS

Ginkgo ran 1 suite in 4.13106253s
Test Suite Passed
```

### CODE REVIEW

**Comment by radtriste** [comment]
@jerichokeyne Please run `make lint` and review the issues. Some lines may be too big

**Comment by jerichokeyne** [comment]
@radtriste the linting issue should be fixed now

**Review by radtriste — APPROVED** [review]
/lgtm

**Pull request merged**
