### PR TITLE
OCM-4721 | fix: update hcp billing account link

### PR DESCRIPTION
**Pull request by chenz4027**
https://issues.redhat.com/browse/OCM-4721

### CODE REVIEW

**Review by robpblake — COMMENTED** [review]
/lgtm

**Review by robpblake — APPROVED** [review]

**Comment by robpblake** [comment]
@zgalor This one is asking for your +1.

cheers,

Rob

**Comment by zgalor** [comment]
LGTM, but this better be approved by someone from the rosa squad

**Pull request merged**
