### PR TITLE
Addon install - add non-interactive commands

### PR DESCRIPTION
**Pull request by oriAdler**
This MR adds printing of additional output for non-interactive commands.

Related: [SDA-5569](https://issues.redhat.com/browse/SDA-5569)

image
image

### CODE REVIEW

**Comment by vkareh** [comment]
/hold

@oriAdler this is already supported, please don't hard-code addon parameters in ROSA, as ROSA should be agnostic to whatever addon parameters are in place.

This is from my `master` branch:
```
$ rosa install addon -c oadler-loggi cluster-logging-operator --use-cloudwatch true --use-app-logs true --use-infra-logs true --use-audit-logs true --cloudwatch-region us-east-1 
? Are you sure you want to install add-on 'cluster-logging-operator' on cluster 'oadler-loggi'? Yes
I: Add-on 'cluster-logging-operator' is now installing. To check the status run 'rosa list addons -c oadler-loggi'
```

**Comment by ciaranRoche** [comment]
Changes look good to me thanks Ori, will leave it to victor to unhold this :smiley_cat:

**Pull request merged**
