### PR TITLE
Update OWNERS file

### PR DESCRIPTION
**Pull request by vkareh**
Adding @tbrisker as a repo maintainer to automatically run pipelines.

### CODE REVIEW

**Comment by tbrisker** [comment]
@vkareh @igoihman looks like i need to be added to the openshift org, how do i do that?

**Comment by vkareh** [comment]
@tbrisker, you'll need to follow the steps here: https://source.redhat.com/groups/public/atomicopenshift/atomicopenshift_wiki/openshift_onboarding_checklist_for_github

**Comment by tbrisker** [comment]
@vkareh I'm now a proud member of the organization. Though I'm not sure I want to be part of an organization that accepts people like me as members 😆

**Comment by vkareh** [comment]
> @vkareh I'm now a proud member of the organization. Though I'm not sure I want to be part of an organization that accepts people like me as members laughing

Too late - you're stuck with us now :stuck_out_tongue_winking_eye:

**Pull request merged**
