### PR TITLE
sts: Ensure operator IAM roles

### PR DESCRIPTION
**Pull request by vkareh**
When creating an STS cluster, operator IAM roles are mandatory to ensure
proper cluster installation. We now validate that there are operator IAM
roles included in the payload, otherwise we error out with a message
describing the process for extracting the credentials requests.

### CODE REVIEW

**Comment by pvasant** [comment]
LGTM

**Comment by vkareh** [comment]
@pvasant thanks - you are actually part of the `OWNERS` file in this repo, so saying `/lgtm` should be sufficient to approve/merge automatically :) (https://github.com/openshift/rosa/pull/358)

**Comment by vkareh** [comment]
> @vkareh: you cannot LGTM your own PR.

:facepalm:

**Pull request merged**
