### PR TITLE
Select a single subnet for a single AZ machine pool - BYOVPC clusters

### PR DESCRIPTION
**Pull request by oriAdler**
1. Add the `subnet` flag to the `create machine pool` command.
2. Add functions to fetch VPC's private subnets.

Possible flows:
1. BYOVPC single AZ cluster - the user is prompted with the option to select subnet.
2. BYOVPC multi-AZ cluster - if the user chooses a single AZ, they have the option
to provide a subnet or an availability zone.

Related: [SDA-6289](https://issues.redhat.com/browse/SDA-6289)

[select_subnet_for_single_az_machine_pool.webm](https://user-images.githubusercontent.com/57869309/176680592-b632f2f6-8fdb-44de-8d89-22a115eef6f6.webm)

### CODE REVIEW

**Comment by oriAdler** [comment]
[test]

**Comment by tbrisker** [comment]
@oriAdler can you please split out the sdk upgrade from the actual code change? And if the code change has two parts, splitting that into smaller commits/separate PRs makes review much easier.

**Comment by oriAdler** [comment]
> @oriAdler can you please split out the sdk upgrade from the actual code change? And if the code change has two parts, splitting that into smaller commits/separate PRs makes review much easier.
@tbrisker sure, I'll create a separate MR for the SDK upgrade.

**Comment by pvasant** [comment]
LGTM @zgalor  please stamp it once your are done reviewing

**Comment by zgalor** [comment]
LGTM

**Pull request merged**
