### PR TITLE
OCM-2220 | feat: support list dns domains in rosa cli

### PR DESCRIPTION
**Pull request by marcolan018**
Signed-off-by: marcolan018 <llan@redhat.com>

### CODE REVIEW

**Comment by oriAdler** [comment]
Overall LGTM.
Can you please paste an example of the command output?
Is this PR dependent on the backend change https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/6017?

**Comment by marcolan018** [comment]
@oriAdler 
yes, this pr depends on https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/6017

here is a sample output:
```
bash-5.2$ ./rosa list dns-domains
ID                    CLUSTER ID                        RESERVED TIME
4sd4.i1.devshift.org  23qbalg18ilfrt7f85qa6f0ised71ojn  2023-05-19T00:04:56-05:00
7efn.i1.devshift.org                                    2023-06-13T21:34:36-05:00
8mrp.i1.devshift.org  23u50b1fqvqtg2e57p4gss5eapi7jnmu  2023-05-24T18:31:01-05:00
axqr.i1.devshift.org                                    2023-06-08T22:16:34-05:00
b3hz.i1.devshift.org  23qpng0431m1empd1omn85n7satolj2m  2023-05-19T16:27:36-05:00
bflq.i1.devshift.org                                    2023-06-10T03:18:51-05:00
buqw.i1.devshift.org                                    2023-06-10T01:55:58-05:00
cndm.i1.devshift.org                                    2023-06-10T01:07:09-05:00
d3gv.i1.devshift.org                                    2023-06-08T22:54:54-05:00
fm0e.i1.devshift.org                                    2023-06-15T11:15:53-05:00
l2bt.i1.devshift.org                                    2023-06-10T02:07:53-05:00
l6yb.i1.devshift.org                                    2023-06-12T10:10:38-05:00
nwlf.i1.devshift.org                                    2023-06-08T23:45:47-05:00
rvlj.i1.devshift.org                                    2023-06-10T19:38:52-05:00
xpr4.i1.devshift.org                                    2023-06-13T22:59:36-05:00
ys3w.i1.devshift.org                                    2023-06-10T02:57:21-05:00
```

**Comment by oriAdler** [comment]
LGTM

**Pull request merged**
