### PR TITLE
go: Bump version to 1.18

### PR DESCRIPTION
**Pull request by vkareh**
- Fixes https://issues.redhat.com/browse/SDA-6707
- Fixes https://issues.redhat.com/browse/SDA-6706
- Fixes https://issues.redhat.com/browse/SDA-6626
- Fixes https://issues.redhat.com/browse/SDA-6602
- Fixes https://issues.redhat.com/browse/SDA-6601
- Fixes https://issues.redhat.com/browse/SDA-6594
- Fixes https://issues.redhat.com/browse/SDA-6545
- Fixes https://issues.redhat.com/browse/SDA-6539
- Fixes https://issues.redhat.com/browse/SDA-6538
- Fixes https://issues.redhat.com/browse/SDA-6537
- Fixes https://issues.redhat.com/browse/SDA-6514
- Fixes https://issues.redhat.com/browse/SDA-6458
- Fixes https://issues.redhat.com/browse/SDA-6455
- Fixes https://issues.redhat.com/browse/SDA-6238
- Fixes https://issues.redhat.com/browse/SDA-5346

### CODE REVIEW

**Comment by vkareh** [comment]
/hold

Until the release pipelines are also updated

**Comment by vkareh** [comment]
Needs https://github.com/openshift/release/pull/32404

**Comment by tbrisker** [comment]
🥳 looks like this also requires some updates to the linter though

**Pull request merged**
