### PR TITLE
Add StopInstances action to support Hibernation

### PR DESCRIPTION
**Pull request by jharrington22**
To support Hibernation we need the following policies added to the Installer policy so that Hive can operate on the EC2 instances state.

```
ec2.DescribeInstances
ec2.StartInstances
ec2.TerminateInstances
ec2.StopInstances
```

This PR adds the missing `ec2:StopInstances` and `ec2:StartInstances` permissions.

[OSD-8441](https://issues.redhat.com/browse/OSD-8441) 
[SDA-4806](https://issues.redhat.com/browse/SDA-4806)

### CODE REVIEW

**Comment by vkareh** [comment]
@jharrington22 can you run `make generate`?

**Comment by vkareh** [comment]
/hold cancel
Thanks

**Comment by jharrington22** [comment]
@vkareh yeap, good to go.

**Pull request merged**
