### PR TITLE
Allow setting 0 replicas to autoscaling machine pool (Not default)

### PR DESCRIPTION
**Pull request by zgalor**
This is blocked until this is supported in CS backend

### CODE REVIEW

**Comment by zgalor** [comment]
@vkareh @nimrodshn PTAL

**Comment by vkareh** [comment]
/hold
until https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/2844 is merged

**Comment by zgalor** [comment]
@vkareh this is now ready to be merged

**Pull request merged**
