### PR TITLE
command to list parameters of add-on installation

### PR DESCRIPTION
**Pull request by renan-campos**
== Describe Add-on Installation sample output start ==

Id:                          bar
Href:                        /api/clusters_mgmt/v1/clusters/foo/addons/bar
Addon state:                 ready
Parameters:
        "id_1"                      : "value_1"
        "id_2"                      : "value_2"

== Describe Add-on Installation sample output end ==

### CODE REVIEW

**Review by ciaranRoche — COMMENTED** [review]
Works well, can we split this into two MR's

Remove the reader interface and test to a seperate MR, would like to get the ROSA experts to have a look on that approach. Where as we can just merge the describe function on its own.

**Comment by ciaranRoche** [comment]
@renan-campos If there is not a Jira for this, can you create one and link them, just so we can get this through QE

**Comment by renan-campos** [comment]
> @renan-campos If there is not a Jira for this, can you create one and link them, just so we can get this through QE

will do

**Comment by ciaranRoche** [comment]
!JIRA - SDA-6174

**Pull request merged**
