### PR TITLE
[SDA-6997] Bump ocm sdk

### PR DESCRIPTION
**Pull request by gdbranco**
Related issues: https://issues.redhat.com/browse/SDA-6997
# What
Bump ocm sdk version

# Why
Get new CA for windows

### CODE REVIEW

**Comment by vkareh** [comment]
@gdbranco you also need to run `go mod vendor` and re-compile to ensure that any SDK API changes are accounted for.

**Comment by gdbranco** [comment]
> @gdbranco you also need to run `go mod vendor` and re-compile to ensure that any SDK API changes are accounted for.

@vkareh Oh I wasn't sure I needed, but I did do that

**Comment by pvasant** [comment]
Do we need to run  'go mod tidy`? i see too many changes

**Comment by gdbranco** [comment]
> Do we need to run 'go mod tidy`? i see too many changes

Did it

**Pull request closed without merging**
