### PR TITLE
Edit machinepool min replicas

### PR DESCRIPTION
**Pull request by oriAdler**
Check if the min/max replicas value was updated, to differentiate the zero default value of the flags from the user input.

**Note:** Zero value for min/max replicas is a valid value.

Related: [SDA-7905](https://issues.redhat.com/browse/SDA-7905)

image

### CODE REVIEW

**Comment by oriAdler** [comment]
@zgalor @lucasponce @hunterkepley PTAL

**Comment by zgalor** [comment]
Thinking out loud if it wouldn't be simpler to set the default to -1?

**Comment by oriAdler** [comment]
> Thinking out loud if it wouldn't be simpler to set the default to -1?

That might work, but I'm not sure if we should set the default value to an invalid value (also to be consistent with other commands we usually set the default value to zero/false/empty string).
With that being said I don't mind taking this approach if you think it simplifies the flow.

**Comment by zgalor** [comment]
It simplifies, but less clear, so let's keep it.

**Comment by zgalor** [comment]
LGTM

**Pull request merged**
