### PR TITLE
Bump OCM SDK version to v0.1.199

### PR DESCRIPTION
**Pull request by vkareh**
This new version of the OCM SDK uses golang-jwt/jwt instead of
dgrijalva/jwt-go. We match the behaviour by swapping the module on our
side as well.

### CODE REVIEW

**Review by jhernand — APPROVED** [review]
Looks good to me.

**Comment by jhernand** [comment]
@vkareh the new JWT library uses some Go 1.15 methods, so you will need to update the project to use at least Go 1.15.

**Comment by vkareh** [comment]
> @vkareh the new JWT library uses some Go 1.15 methods, so you will need to update the project to use at least Go 1.15.

Ah, thanks @jhernand - Also realised that openshift/release forces golang-1.14 on the pipeline

**Comment by vkareh** [comment]
@jhernand - this is needed too: https://github.com/openshift/release/pull/21032

**Comment by jhernand** [comment]
While at it it may be worth to update to Go 1.16 already.

**Comment by vkareh** [comment]
The problem with 1.16 is that I'm not entirely sure if RHEL already supports 1.16.6, and I need to build it in a version supported by RHEL. Any ideas how to check?

**Review by jhernand — APPROVED** [review]
Looks good to me.

**Pull request merged**
