### PR TITLE
OCM-11482 | fix: loosen registry regex check

### PR DESCRIPTION
**Pull request by chenz4027**
https://issues.redhat.com/browse/OCM-11484

### CODE REVIEW

**Review by andreadecorte — APPROVED** [review]
I see that you already have tests on it, so I think we're good on that

**Comment by chenz4027** [comment]
> I see that you already have tests on it, so I think we're good on that

@andreadecorte Yeah before the regex was more strict to only allow ".". Since we don't really restrict the name validation in the backend, cli will align.

**Pull request merged**
