### PR TITLE
OCM-5958 | chore: Move release scripts from Wiki to Git repository

### PR DESCRIPTION
**Pull request by robpblake**
This PR moves the scripts used to manage parts of the ROSA release from our Wiki into the Git repository for the project. Once merged, I will update the wiki to reference these scripts instead.

All scripts have been named (or renamed) to follow the pattern `release-<function>.sh`

Legacy scripts that are no longer required have been removed.

### CODE REVIEW

**Comment by thomasmckay** [comment]
i'm +1 on this but at least an initial note in hack's README.md would be good imo

**Comment by robpblake** [comment]
> i'm +1 on this but at least an initial note in hack's README.md would be good imo

@thomasmckay Good catch. I had completely missed that.

**Review by ciaranRoche — APPROVED** [review]
/lgtm

**Pull request merged**
